### ISSUE TITLE
0.0.4 no longer works in an IFrame with third-party cookies disabled.

### ISSUE THREAD

**Issue by Jasu** [bigpipe/env-variable#4]
If third-party cookies are disabled on Chrome, the following line will throw a `DOMException` SecurityError:

```
    if (window.localStorage) {
```

This should probably be wrapped in a try-catch-block, like in 0.0.3.

**Comment by cephalopodMD** [comment]
@3rd-Eden please fix this by either accepting #8 or #7. Consumers of this package shouldn't have to know to specify version 0.0.3.
